// This file is generated by Slice Machine. Update with care!

import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	HeroSlice,
	ImageGrid,
};

export const components = {
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
